"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
'''
__file__ 显示当前文件的位置
项目根目录BASE_DIR为文件所在路径的父级目录的父级目
以前用os.path（如下），太长了
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
'''
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
'''
对各种需要加密的数据做hash处理
'''
SECRET_KEY = 'django-insecure-@mi$q*ypn9dpe2av%i4=n&=rn6ndp)(r$jj+va_*nyn$vnze5s'

# SECURITY WARNING: don't run with debug turned on in production!
'''
在开发环境中通常设为True
在线上环境通常设为False
'''
DEBUG = True

'''
用于配置可以访问当前站点的域名。
当DEBUG设置为False时，设置ALLOWED_HOSTS = [*]允许所有的域名访问。
'''
ALLOWED_HOSTS = []


# Application definition
'''
这个参数配置的是当前项目需要加载的App包路径列表
'''
INSTALLED_APPS = [
    'django.contrib.admin',  #管理后台
    'django.contrib.auth',   #权限系统
    'django.contrib.contenttypes',
    'django.contrib.sessions',  #会话系统
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

'''
当前项目中需要加载的中间列表配置
'''
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', #处理会话的
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  #用于处理授权验证的
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

'''
标记的是当前项目的根URL配置，是Django路由系统的入口点
'''
ROOT_URLCONF = 'mysite.urls'

'''
这是一个列表变量，用于项目的模板配置。
列表中的每一个元素都是一个字典，每个字典代表一个模板引擎。
Django默认会配置自带的DTL(DjangoTemplates)模板引擎。
'''
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

'''
Django的内置服务器将使用的WSGI应用程序对象的完整Python路径
'''
WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
'''
这是一个字典变量，标识项目的数据库配置。
Django默认使用自带的数据库sqlite3。
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
'''
Django默认提供了一些支持插拔的密码验证器，且可以一次性适配多个。
其主要目的是避免直接通过用户的弱密码配置申请
'''
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
'''
语言环境
'''
LANGUAGE_CODE = 'en-us'
'''
时区
'''
TIME_ZONE = 'Asia/Shanghai'
'''
国际化和本地化
'''
USE_I18N = True

USE_L10N = True
'''
标识对于时区的处理。
如果是True，不论TIME_ZONE设置的是什么，存储到数据库中的时间都是UTC时间。
'''
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
'''
用于标记当前项目中静态资源的存放位置
'''
STATIC_URL = '/static/'


'''
需要添加静态文件的路径
以前使用os.path.join方法拼接文件路径，如下所示：
	STATIC_ROOT = [
    os.path.join(BASE_DIR, "static"),
]
	而如果使用pathlib，我们可以直接使用"/"连接符拼接系统路径。
STATIC_ROOT = [
    BASE_DIR / "static",

'''
#STATIC_ROOT = [BASE_DIR / "static",] #这个写法是错的
STATIC_ROOT = str(BASE_DIR / "static")



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
